[build]
   base = "./client"
   publish = "./build"
   command = "yarn build"

[[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

[[headers]]
   for = "/service-worker.js"
   [headers.values]
     Content-Type = "text/javascript"